spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/empstressmeasure
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
      
server:
  port: 8010